### ISSUE TITLE
Provide build data to job options

### ISSUE THREAD

**Issue by ahonor** [vbehar/jenkins-rundeck-plugin#1]
I have a jenkins job that calls a job via the rundeck plugin.  I would like to define the option value using jenkins build data and have it expanded when the rundeck job is called. 
This would work similar to how an "execute shell" build step can use them.

For example, here several env vars are set for a property named "artifact". 
    artifact=$JOB_URL/$BUILD_NUMBER/artifact/dist/simple-$SVN_REVISION.war

It appears this data is currently not available.

**Comment by vbehar** [comment]
Hi,
yes that's a good idea ! I just released a new version of the plugin (1.2) with this feature, it should be in the Jenkins update center in a few hours (I think it is rebuild every 6 hours or something like that).
Vincent

**Comment by ahonor** [comment]
Just tried 1.3 and it works great. I'll be demo'ing continuous deployment using rundeck, jenkins and your plugin this Tuesday, at SVDevOps!

**Comment by vbehar** [comment]
Great, have a good demo !
