### ISSUE TITLE
feature request: configure multiple rundecks from a single jenkins configuration.

### ISSUE THREAD

**Issue by jeremyd** [vbehar/jenkins-rundeck-plugin#10]
I have multiple rundeck servers but only one jenkins.  I need to be able to run jobs against the various rundecks and not just a single one as supported by the plugin's global options.

**Comment by benh57** [comment]
This would be nice

**Comment by EmilVarona** [comment]
As a minor variation, I have a a rundeck job for restarts but need to run it against multiple node combos in an environment.  Today, this means multiple Jenkins jobs.  I'd like to have a single Jenkins job to call a selection of RD jobs or the same job against multiple distinct nodes groups.

**Comment by drbeka** [comment]
Hi EmilVarona,
I have solved this with one jenkins job, which passes a list of nodes to a rundeck job, the rundeck job calls another rundeck job with the nodes list.

**Comment by drbeka** [comment]
we also need the possibility to call jobs on different rundeck servers from 1 jenkins server. Best would be to store the target rundeck server in the jenkins job configuration.
Is this in development?

**Comment by hokadiri** [comment]
+1
